# Generated by Django 5.2.7 on 2025-10-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='link',
            new_name='link_with_report',
        ),
    ]
