# Generated by Django 5.2.7 on 2025-10-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_emptymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmptyModel',
        ),
    ]
