# Generated by Django 5.2.7 on 2025-10-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='short_size',
            new_name='shirt_size',
        ),
    ]
