# Generated by Django 5.2.7 on 2025-10-03 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_fruit_runner_created_at_alter_runner_medal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['line']},
        ),
        migrations.AlterField(
            model_name='article',
            name='link_with_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.reporter', verbose_name='linked article with its reproter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_name',
            field=models.CharField(max_length=70, verbose_name="person's first name"),
        ),
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ManyToManyField(to='news.publication'),
        ),
    ]
