# Generated by Django 5.2.7 on 2025-10-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_group_person_membership_group_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='invited_person',
            new_name='invited_reason',
        ),
    ]
