# Generated by Django 5.2.7 on 2025-10-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_invited_person_membership_invited_reason'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_person_group',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='groub',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='invited_reason',
        ),
        migrations.AddField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by_memberships', to='news.person'),
        ),
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(through='news.MemberShip', through_fields=('group', 'person'), to='news.person'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('person', 'group'), name='unique_person_group'),
        ),
    ]
