# Generated by Django 5.2.7 on 2025-10-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_membership_unique_person_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
